// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhfRz-LyfBoZIV1SSJW5QQ8X40j-CG-s',
    appId: '1:696099769430:web:091c91b07d616aada33ff7',
    messagingSenderId: '696099769430',
    projectId: 'tiendapreentrenos',
    authDomain: 'tiendapreentrenos.firebaseapp.com',
    storageBucket: 'tiendapreentrenos.firebasestorage.app',
    measurementId: 'G-ESGH13Q42E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnQ145dY4uiMuhX1BHMlfcQVSFr6COfT8',
    appId: '1:696099769430:android:0b49b1bd56edb677a33ff7',
    messagingSenderId: '696099769430',
    projectId: 'tiendapreentrenos',
    storageBucket: 'tiendapreentrenos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7OnPiKY0xtZZbIr27NGHQDK7O3W-9kc',
    appId: '1:696099769430:ios:0c89410194605e79a33ff7',
    messagingSenderId: '696099769430',
    projectId: 'tiendapreentrenos',
    storageBucket: 'tiendapreentrenos.firebasestorage.app',
    iosClientId: '696099769430-vkhcm8nnk6li3fkulv2u18n2vlusnnci.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7OnPiKY0xtZZbIr27NGHQDK7O3W-9kc',
    appId: '1:696099769430:ios:0c89410194605e79a33ff7',
    messagingSenderId: '696099769430',
    projectId: 'tiendapreentrenos',
    storageBucket: 'tiendapreentrenos.firebasestorage.app',
    iosClientId: '696099769430-vkhcm8nnk6li3fkulv2u18n2vlusnnci.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAhfRz-LyfBoZIV1SSJW5QQ8X40j-CG-s',
    appId: '1:696099769430:web:8e606609cc818993a33ff7',
    messagingSenderId: '696099769430',
    projectId: 'tiendapreentrenos',
    authDomain: 'tiendapreentrenos.firebaseapp.com',
    storageBucket: 'tiendapreentrenos.firebasestorage.app',
    measurementId: 'G-9V4SN00NQW',
  );
}
